# Generated by Django 3.2.11 on 2022-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='选手游戏ID')),
                ('qq', models.CharField(max_length=32, verbose_name='QQ号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('type_of_team', models.SmallIntegerField(choices=[(1, '队套'), (2, '传奇套'), (3, '非整套')], verbose_name='球队类型')),
                ('highest_rank', models.SmallIntegerField(verbose_name='单排历史最高段位')),
            ],
        ),
    ]
