# Generated by Django 3.2.11 on 2022-03-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(verbose_name='比赛日期')),
                ('home_goal', models.SmallIntegerField(verbose_name='主队进球数')),
                ('away_goal', models.SmallIntegerField(verbose_name='客队进球数')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='tournament.participant', verbose_name='客队')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='tournament.participant', verbose_name='主队')),
            ],
        ),
    ]
