# Generated by Django 3.2.11 on 2022-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='highest_rank',
            field=models.SmallIntegerField(choices=[(1, '青铜'), (2, '白银'), (3, '黄金'), (4, '钻石'), (5, '挑战者1')], default=1, verbose_name='单排历史最高段位'),
        ),
    ]
