# Generated by Django 3.2.11 on 2022-03-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20220319_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='drwas',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='losts',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='points',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='wins',
        ),
    ]
