# Generated by Django 3.2.11 on 2022-03-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_rename_host_game_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='drwas',
            new_name='draws',
        ),
    ]
