# Generated by Django 3.2.11 on 2022-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_rename_drwas_participant_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='games',
            field=models.SmallIntegerField(default=0, verbose_name='比赛数'),
        ),
    ]
