# Generated by Django 3.2.11 on 2022-03-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_participant_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_rank',
            field=models.SmallIntegerField(default=0, verbose_name='排名'),
        ),
    ]
