# Generated by Django 3.2.11 on 2022-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.CharField(choices=[(1, '新旅程杯'), (2, '不存在的杯')], default=1, max_length=32, verbose_name='赛事名称'),
        ),
    ]
