# Generated by Django 3.2.11 on 2022-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_game_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(default='111', max_length=16, verbose_name='登录密码'),
        ),
    ]
