# Generated by Django 3.2.11 on 2022-03-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_participant_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='games',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='losts',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='points',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='wins',
        ),
    ]
