# Generated by Django 3.2.11 on 2022-03-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_auto_20220331_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewJourneyCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0, verbose_name='积分')),
                ('wins', models.SmallIntegerField(default=0, verbose_name='胜场数')),
                ('draws', models.SmallIntegerField(default=0, verbose_name='平场数')),
                ('losts', models.SmallIntegerField(default=0, verbose_name='负场数')),
                ('games', models.SmallIntegerField(default=0, verbose_name='比赛数')),
                ('goals', models.SmallIntegerField(default=0, verbose_name='进球数')),
                ('goals_conceded', models.SmallIntegerField(default=0, verbose_name='失球数')),
                ('current_rank', models.SmallIntegerField(default=0, verbose_name='排名')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.participant', verbose_name='参赛者')),
            ],
        ),
        migrations.CreateModel(
            name='FakeCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0, verbose_name='积分')),
                ('wins', models.SmallIntegerField(default=0, verbose_name='胜场数')),
                ('draws', models.SmallIntegerField(default=0, verbose_name='平场数')),
                ('losts', models.SmallIntegerField(default=0, verbose_name='负场数')),
                ('games', models.SmallIntegerField(default=0, verbose_name='比赛数')),
                ('goals', models.SmallIntegerField(default=0, verbose_name='进球数')),
                ('goals_conceded', models.SmallIntegerField(default=0, verbose_name='失球数')),
                ('current_rank', models.SmallIntegerField(default=0, verbose_name='排名')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.participant', verbose_name='参赛者')),
            ],
        ),
    ]
