# Generated by Django 3.2.11 on 2022-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_fakecup_newjourneycup'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_rank',
            field=models.SmallIntegerField(default=0, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='participant',
            name='draws',
            field=models.SmallIntegerField(default=0, verbose_name='平场数'),
        ),
        migrations.AddField(
            model_name='participant',
            name='games',
            field=models.SmallIntegerField(default=0, verbose_name='比赛数'),
        ),
        migrations.AddField(
            model_name='participant',
            name='goals',
            field=models.SmallIntegerField(default=0, verbose_name='进球数'),
        ),
        migrations.AddField(
            model_name='participant',
            name='goals_conceded',
            field=models.SmallIntegerField(default=0, verbose_name='失球数'),
        ),
        migrations.AddField(
            model_name='participant',
            name='losts',
            field=models.SmallIntegerField(default=0, verbose_name='负场数'),
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='participant',
            name='wins',
            field=models.SmallIntegerField(default=0, verbose_name='胜场数'),
        ),
    ]
