# Generated by Django 3.2.11 on 2022-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_auto_20220331_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.SmallIntegerField(choices=[(1, '新旅程杯'), (2, '不存在的杯')], default=1, verbose_name='赛事名称'),
        ),
    ]
