# Generated by Django 3.2.11 on 2022-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_game_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.SmallIntegerField(choices=[(1, '新旅程杯'), (2, '不存在的杯')], default=1, verbose_name='赛事'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(default='111', max_length=64, verbose_name='登录密码'),
        ),
    ]
